<h1>Loan Status Prediction</h1>

Credit Risk Models are one of the most successful applications of data science. 
Given a set of information for a user, predict how 'reliable' she is in terms of being financially stable.
These models have raised many discussions concerning privacy, racial profiling etc.

We will be using an anonymized dataset that consists of a list of a bank's users.
You may find the dataset [here](https://www.kaggle.com/zaurbegiev/my-dataset).

Let us first install sklearn and numpy libraries:

In [6]:
!pip install sklearn
!pip install numpy

Requirement already satisfied: sklearn in /Users/skenderi/.conda/envs/dl/lib/python3.6/site-packages (0.0)
Requirement already satisfied: scikit-learn in /Users/skenderi/.conda/envs/dl/lib/python3.6/site-packages (from sklearn) (0.22.1)
Requirement already satisfied: numpy>=1.11.0 in /Users/skenderi/.conda/envs/dl/lib/python3.6/site-packages (from scikit-learn->sklearn) (1.18.1)
Requirement already satisfied: joblib>=0.11 in /Users/skenderi/.conda/envs/dl/lib/python3.6/site-packages (from scikit-learn->sklearn) (0.14.1)
Requirement already satisfied: scipy>=0.17.0 in /Users/skenderi/.local/lib/python3.6/site-packages (from scikit-learn->sklearn) (1.4.1)
Requirement already satisfied: numpy in /Users/skenderi/.conda/envs/dl/lib/python3.6/site-packages (1.18.1)

Now let's import all the required libraries.

In [8]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import preprocessing
from sklearn.impute import SimpleImputer as Imputer
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import mean_squared_error, accuracy_score
from sklearn.linear_model import SGDClassifier, LogisticRegression
from sklearn.svm import SVC
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter(action='ignore', category=DeprecationWarning)

In [9]:
# Load the data to a pandas dataframe
df = pd.read_csv("credit_train.csv")
df.head()

,Loan ID,Customer ID,Loan Status,Current Loan Amount,Term,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,14dd8831-6af5-400b-83ec-68e61888a048,981165ec-3274-42f5-a3b4-d104041a9ca9,Fully Paid,445412.0,Short Term,709.0,1167493.0,8 years,Home Mortgage,Home Improvements,5214.74,17.2,NaN,6.0,1.0,228190.0,416746.0,1.0,0.0
1,4771cc26-131a-45db-b5aa-537ea4ba5342,2de017a3-2e01-49cb-a581-08169e83be29,Fully Paid,262328.0,Short Term,NaN,NaN,10+ years,Home Mortgage,Debt Consolidation,33295.98,21.1,8.0,35.0,0.0,229976.0,850784.0,0.0,0.0
2,4eed4e6a-aa2f-4c91-8651-ce984ee8fb26,5efb2b2b-bf11-4dfd-a572-3761a2694725,Fully Paid,99999999.0,Short Term,741.0,2231892.0,8 years,Own Home,Debt Consolidation,29200.53,14.9,29.0,18.0,1.0,297996.0,750090.0,0.0,0.0
3,77598f7b-32e7-4e3b-a6e5-06ba0d98fe8a,e777faab-98ae-45af-9a86-7ce5b33b1011,Fully Paid,347666.0,Long Term,721.0,806949.0,3 years,Own Home,Debt Consolidation,8741.90,12.0,NaN,9.0,0.0,256329.0,386958.0,0.0,0.0
4,d4062e70-befa-4995-8643-a0de73938182,81536ad9-5ccf-4eb8-befb-47a4d608658e,Fully Paid,176220.0,Short Term,NaN,NaN,5 years,Rent,Debt Consolidation,20639.70,6.1,NaN,15.0,0.0,253460.0,427174.0,0.0,0.0

In [15]:
def siivoaData(data, slice=1.0):

    # Mikä on muuttuja josta olemme kiinnostuneita?
    # Haluamme tietysti ymmärtää muuttujaa lainan tilanne "Loan staus"
    # Dikotominne muuttuja kuvaa sitä maksetaanko laina takaisin vai ei.

    #Haluammeko poistaa jotain muuttujia?
    poistettavatMuuttujat = ['Loan ID','Customer ID']
    data = data.drop(poistettavatMuuttujat, axis=1)

    #Annetaan keskiarvot puutuville tietopisteille
    sarakkeet =['Current Loan Amount','Credit Score','Annual Income','Years of Credit History',
            'Months since last delinquent','Number of Open Accounts','Number of Credit Problems',
           'Current Credit Balance','Maximum Open Credit','Bankruptcies','Tax Liens']
    muuttujanTäyttäjä = Imputer()
    data[sarakkeet] = muuttujanTäyttäjä.fit_transform(data[sarakkeet])
    data[sarakkeet] = data[sarakkeet].astype(int)

    #Poistetaan vielä NaN rivit
    data=data.dropna()

    #Note:  Discarding half of the data for testing purposes!
    if slice in (0, 1):
        mid_point = int(len(data)*slice)
        data = data.loc[:mid_point]


    #Valitaan muuttuja josta olemme kiinnostuneita ja koodataan se
    y = data['Loan Status']
    new_y = []
    for i in y:
        if i == 'Fully Paid':
            new_y.append(1)
        else:
            new_y.append(0)
    data = data.drop('Loan Status', axis=1)

    # Koodataan kategoriset muuttujat
    data = pd.get_dummies(data)
    #print(data.head())

    # Normalisoidaan data
    # Palautamme myös dataMean ja dataDev arvot jos haluamme syöttää koneelle uusia havaintoja
    dataMean = np.mean(data, axis=0)
    dataDev = np.std(data, axis=0)
    norm_x= (data - dataMean) / dataDev

    x = data.values #muutetaan numpy array
    min_max_scaler = preprocessing.MinMaxScaler()
    x_scaled = min_max_scaler.fit_transform(x)
    normMinMax = pd.DataFrame(x_scaled)

    return norm_x, normMinMax, data, new_y, dataMean, dataDev

xNorm, xMinMax, xNoNorm, y, xMean, xDev = siivoaData(df, slice=0.5)

In [16]:
#Check how xNorm, xMinMax and xNoNorm dataframes look like
xNoNorm

,Current Loan Amount,Credit Score,Annual Income,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,...,Purpose_Medical Bills,Purpose_Other,Purpose_Take a Trip,Purpose_major_purchase,Purpose_moving,Purpose_other,Purpose_renewable_energy,Purpose_small_business,Purpose_vacation,Purpose_wedding
0,445412,709,1167493,5214.74,17,34,6,1,228190,416746,...,0,0,0,0,0,0,0,0,0,0
1,262328,1076,1378276,33295.98,21,8,35,0,229976,850784,...,0,0,0,0,0,0,0,0,0,0
2,99999999,741,2231892,29200.53,14,29,18,1,297996,750090,...,0,0,0,0,0,0,0,0,0,0
3,347666,721,806949,8741.90,12,34,9,0,256329,386958,...,0,0,0,0,0,0,0,0,0,0
4,176220,1076,1378276,20639.70,6,34,15,0,253460,427174,...,0,0,0,0,0,0,0,0,0,0
5,206602,7290,896857,16367.74,17,34,6,0,215308,272448,...,0,0,0,0,0,0,0,0,0,0
6,217646,730,1184194,10855.08,19,10,13,1,122170,272052,...,0,0,0,0,0,0,0,0,0,0
7,648714,1076,1378276,14806.13,8,8,15,0,193306,864204,...,0,0,0,0,0,0,0,0,0,0
8,548746,678,2559110,18660.28,22,33,4,0,437171,555038,...,0,0,0,0,0,0,0,0,0,0
9,215952,739,1454735,39277.75,13,34,20,0,669560,1021460,...,0,0,0,0,0,0,0,0,0,0
10,99999999,728,714628,11851.06,16,76,16,0,203965,289784,...,0,0,0,0,0,0,0,0,0,0
11,541970,1076,1378276,23568.55,23,34,23,0,60705,1634468,...,0,0,0,0,0,0,0,0,0,0
12,99999999,740,776188,11578.22,8,25,6,0,134083,220220,...,0,0,0,0,0,0,0,0,0,0
13,99999999,743,1560907,17560.37,13,34,10,1,225549,496474,...,0,0,0,0,0,0,0,0,0,0
14,234124,727,693234,14211.24,24,46,10,1,28291,107052,...,0,0,0,0,0,0,0,0,0,0
15,449020,1076,1378276,18904.81,19,34,8,0,334533,428956,...,0,0,0,0,0,0,0,0,0,0
16,653004,1076,1378276,14537.09,20,34,9,0,302309,413754,...,0,0,0,0,0,0,0,0,0,0
17,666204,723,1821967,17612.24,22,34,15,0,813694,2004618,...,0,0,0,0,0,0,0,0,0,0
18,66396,1076,1378276,9898.81,27,34,23,1,9728,402380,...,0,0,0,0,0,0,0,0,0,0
19,390390,747,1791738,2478.55,22,34,6,0,121182,801812,...,0,0,0,0,0,0,0,0,0,0
20,317108,687,1133274,9632.81,17,53,4,0,60287,126940,...,0,0,0,0,0,0,0,0,0,0
21,128238,750,1354073,13202.15,11,34,7,0,131936,458788,...,0,0,0,0,0,0,0,0,0,0
22,153252,714,1890690,21900.35,15,34,12,0,891594,1081014,...,0,0,0,0,0,0,0,0,0,0
23,91894,724,850383,5860.74,17,34,7,0,95608,230626,...,0,0,0,0,0,0,0,0,0,0
24,244926,704,1249953,6812.26,14,34,6,1,143051,245014,...,0,0,0,0,0,0,0,0,0,0
25,465410,688,1722654,15647.45,22,30,7,0,107559,488356,...,0,0,0,0,0,0,0,0,0,0
26,99999999,724,1029857,13817.18,12,34,6,0,138339,221232,...,0,0,0,0,0,0,0,0,0,0
27,443960,749,1432391,25186.21,14,34,15,0,342475,905344,...,0,0,0,0,0,0,0,0,0,0
28,99999999,746,1749748,19247.19,20,32,17,0,224390,295240,...,0,0,0,0,0,0,0,0,0,0
30,99999999,737,1501912,31039.54,18,34,8,0,229349,469172,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47860,109076,1076,1378276,659.30,8,34,6,0,4389,28402,...,0,0,0,0,0,1,0,0,0,0
47861,169136,708,490770,2200.20,9,34,5,0,104880,207570,...,0,0,0,0,0,0,0,0,0,0
47862,715902,1076,1378276,17018.30,17,34,8,0,689586,11246136,...,0,0,0,0,0,0,0,0,0,0
47863,349536,1076,1378276,25250.24,21,34,16,0,382052,847462,...,0,0,0,0,0,0,0,0,0,0
47864,213906,1076,1378276,18376.04,6,34,8,0,59508,675510,...,0,0,0,0,0,1,0,0,0,0
47865,223454,7200,656146,13068.20,11,34,8,1,163058,920964,...,0,0,0,0,0,0,0,0,0,0
47866,293810,709,810445,5808.30,17,11,10,0,208905,331342,...,0,0,0,0,0,0,0,0,0,0
47867,208296,746,655823,13225.71,11,34,9,0,222300,509718,...,0,0,0,0,0,0,0,0,0,0
47868,99999999,749,1894110,3803.99,22,34,8,0,195928,1758614,...,0,0,0,0,0,0,0,0,0,0
47869,784410,1076,1378276,12975.48,16,42,6,0,538232,721314,...,0,0,0,0,0,0,0,0,0,0
47870,22418,716,774364,12518.91,11,34,6,0,7030,312972,...,0,0,0,0,0,0,0,0,0,0
47871,179454,714,1484888,9614.57,23,34,13,1,40736,109714,...,0,0,0,0,0,0,0,0,0,0
47872,439032,7240,2566691,37430.95,28,35,12,0,61807,137390,...,0,0,0,0,0,0,0,0,0,0
47873,434764,727,1070118,22115.62,21,34,8,0,196992,245542,...,0,0,0,0,0,0,0,0,0,0
47874,215578,619,791274,6857.67,14,74,5,0,106343,159500,...,0,0,0,0,0,0,0,0,0,0
47875,99999999,725,1541432,4958.24,13,23,9,0,65512,689590,...,0,0,0,0,0,0,0,0,0,0
47876,92862,1076,1378276,6529.73,12,34,11,0,11438,81752,...,0,0,0,0,0,1,0,0,0,0
47877,671154,687,1197912,25255.94,14,79,9,0,284829,729652,...,0,0,0,0,0,0,0,0,0,0
47878,99999999,745,1113210,5658.77,11,21,10,0,188271,388564,...,0,0,0,0,0,0,0,0,0,0
47879,241428,722,739214,11149.96,20,34,7,1,48279,142582,...,0,0,0,0,0,0,0,0,0,0
47880,559262,1076,1378276,23307.11,14,34,18,0,14478,2393710,...,0,0,0,0,0,0,0,0,0,0
47881,99999999,695,1164947,19803.89,15,0,12,0,373996,656128,...,0,0,0,0,0,0,0,0,0,0
47882,96294,1076,1378276,9476.82,24,20,6,0,69597,137280,...,0,0,0,0,0,0,0,0,0,0
47883,65010,739,785954,19255.74,27,34,22,0,141550,376772,...,0,0,0,0,0,0,0,0,0,0
47884,561176,711,3625048,42986.93,26,34,10,0,841757,1324290,...,0,0,0,0,0,0,0,0,0,0
47885,474584,1076,1378276,25706.05,18,34,11,0,230451,364034,...,0,0,0,0,0,0,0,0,0,0
47886,99999999,732,1293881,3590.62,16,34,5,0,80294,122980,...,0,0,0,0,0,0,0,0,0,0
47887,518386,720,1305794,16213.65,31,34,12,1,282397,388806,...,0,0,0,0,0,0,0,0,0,0
47888,527208,727,1365948,24131.71,19,34,12,0,663746,1325082,...,0,0,0,0,0,0,0,0,0,0
47889,130504,714,1314838,24653.26,18,43,11,0,329555,510818,...,0,0,0,0,0,0,0,0,0,0

Next we will see how we get different predictive performances by using the raw features vs the two other feature normalization techniques.

In [3]:
cases = []

for x in [xNorm, xMinMax, xNoNorm]:
    case = {}
    case['x_train'], case['x_test'], case['y_train'], case['y_test'] = train_test_split(x, y, test_size= 0.25, random_state=33)
    cases.append(case)

classifiers = [SGDClassifier(), LogisticRegression(), SVC()]

for i, case in enumerate(cases):
    print("Evaluating the models with data from the case #{}".format(i+1))
    for j, clf in enumerate(classifiers):
        #train model with train data
        clf.fit(X=case['x_train'], y=case['y_train'])
        #predict test data
        predictions = clf.predict(X=case['x_test'])
        #calculate the accuracy
        accuracy = accuracy_score(case['y_test'], predictions)

        print("\t Classifier #{} achieved {} accuracy on test data.".format(j+1, accuracy))


# Implement Cross Validation using Logistic Regression classifier
# Using MinMax Normalized data given it performed better
print("Running Cross-Validation using Logistic Regression classifier \n"
    +"and MinMax-Normalized data given it performed better...")
clf = LogisticRegression()
# Use all data available (slice=1.0):
xNorm, xMinMax, xNoNorm, y, xMean, xDev = siivoaData(df, slice=1.0)
# 5 fold cross validation
scores = cross_val_score(clf, xMinMax, y, verbose=1, cv=5)

print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Evaluating the models with data from the case #1
	 Classifier #1 achieved 0.8304552590266876 accuracy on test data.
	 Classifier #2 achieved 0.8332461189604047 accuracy on test data.
	 Classifier #3 achieved 0.833943833943834 accuracy on test data.
Evaluating the models with data from the case #2
	 Classifier #1 achieved 0.8342926914355486 accuracy on test data.

/Users/skenderi/.conda/envs/dl/lib/python3.6/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

	 Classifier #2 achieved 0.8341182626896912 accuracy on test data.
	 Classifier #3 achieved 0.833420547706262 accuracy on test data.
Evaluating the models with data from the case #3
	 Classifier #1 achieved 0.6610849467992325 accuracy on test data.
	 Classifier #2 achieved 0.8292342578056864 accuracy on test data.
	 Classifier #3 achieved 0.7854526425954997 accuracy on test data.
Running Cross-Validation using Logistic Regression classifier
and MinMax-Normalized data given it performed better...

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
/Users/skenderi/.conda/envs/dl/lib/python3.6/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/Users/skenderi/.conda/envs/dl/lib/python3.6/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/Users/skenderi/.conda/envs/dl/lib/python3.6/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/Users/skenderi/.conda/envs/dl/lib/python3.6/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

Accuracy: 0.82 (+/- 0.00)

/Users/skenderi/.conda/envs/dl/lib/python3.6/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    4.2s finished